package com.snilius.suchquick.entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.snilius.suchquick.entity.Shortcut;
import com.snilius.suchquick.entity.IntentExtra;

import com.snilius.suchquick.entity.ShortcutDao;
import com.snilius.suchquick.entity.IntentExtraDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shortcutDaoConfig;
    private final DaoConfig intentExtraDaoConfig;

    private final ShortcutDao shortcutDao;
    private final IntentExtraDao intentExtraDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shortcutDaoConfig = daoConfigMap.get(ShortcutDao.class).clone();
        shortcutDaoConfig.initIdentityScope(type);

        intentExtraDaoConfig = daoConfigMap.get(IntentExtraDao.class).clone();
        intentExtraDaoConfig.initIdentityScope(type);

        shortcutDao = new ShortcutDao(shortcutDaoConfig, this);
        intentExtraDao = new IntentExtraDao(intentExtraDaoConfig, this);

        registerDao(Shortcut.class, shortcutDao);
        registerDao(IntentExtra.class, intentExtraDao);
    }
    
    public void clear() {
        shortcutDaoConfig.getIdentityScope().clear();
        intentExtraDaoConfig.getIdentityScope().clear();
    }

    public ShortcutDao getShortcutDao() {
        return shortcutDao;
    }

    public IntentExtraDao getIntentExtraDao() {
        return intentExtraDao;
    }

}
