package com.snilius.suchquick.entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.snilius.suchquick.entity.Shortcut;
import com.snilius.suchquick.entity.IntentExtra;
import com.snilius.suchquick.entity.Tile;
import com.snilius.suchquick.entity.Launcher;

import com.snilius.suchquick.entity.ShortcutDao;
import com.snilius.suchquick.entity.IntentExtraDao;
import com.snilius.suchquick.entity.TileDao;
import com.snilius.suchquick.entity.LauncherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shortcutDaoConfig;
    private final DaoConfig intentExtraDaoConfig;
    private final DaoConfig tileDaoConfig;
    private final DaoConfig launcherDaoConfig;

    private final ShortcutDao shortcutDao;
    private final IntentExtraDao intentExtraDao;
    private final TileDao tileDao;
    private final LauncherDao launcherDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shortcutDaoConfig = daoConfigMap.get(ShortcutDao.class).clone();
        shortcutDaoConfig.initIdentityScope(type);

        intentExtraDaoConfig = daoConfigMap.get(IntentExtraDao.class).clone();
        intentExtraDaoConfig.initIdentityScope(type);

        tileDaoConfig = daoConfigMap.get(TileDao.class).clone();
        tileDaoConfig.initIdentityScope(type);

        launcherDaoConfig = daoConfigMap.get(LauncherDao.class).clone();
        launcherDaoConfig.initIdentityScope(type);

        shortcutDao = new ShortcutDao(shortcutDaoConfig, this);
        intentExtraDao = new IntentExtraDao(intentExtraDaoConfig, this);
        tileDao = new TileDao(tileDaoConfig, this);
        launcherDao = new LauncherDao(launcherDaoConfig, this);

        registerDao(Shortcut.class, shortcutDao);
        registerDao(IntentExtra.class, intentExtraDao);
        registerDao(Tile.class, tileDao);
        registerDao(Launcher.class, launcherDao);
    }
    
    public void clear() {
        shortcutDaoConfig.getIdentityScope().clear();
        intentExtraDaoConfig.getIdentityScope().clear();
        tileDaoConfig.getIdentityScope().clear();
        launcherDaoConfig.getIdentityScope().clear();
    }

    public ShortcutDao getShortcutDao() {
        return shortcutDao;
    }

    public IntentExtraDao getIntentExtraDao() {
        return intentExtraDao;
    }

    public TileDao getTileDao() {
        return tileDao;
    }

    public LauncherDao getLauncherDao() {
        return launcherDao;
    }

}
