package com.snilius.suchquick.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INTENT_EXTRA".
 */
public class IntentExtra {

    private Long id;
    private String KeyName;
    private String StringProp;
    private Integer IntProp;
    private long shortcutId;

    public IntentExtra() {
    }

    public IntentExtra(Long id) {
        this.id = id;
    }

    public IntentExtra(Long id, String KeyName, String StringProp, Integer IntProp, long shortcutId) {
        this.id = id;
        this.KeyName = KeyName;
        this.StringProp = StringProp;
        this.IntProp = IntProp;
        this.shortcutId = shortcutId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKeyName() {
        return KeyName;
    }

    public void setKeyName(String KeyName) {
        this.KeyName = KeyName;
    }

    public String getStringProp() {
        return StringProp;
    }

    public void setStringProp(String StringProp) {
        this.StringProp = StringProp;
    }

    public Integer getIntProp() {
        return IntProp;
    }

    public void setIntProp(Integer IntProp) {
        this.IntProp = IntProp;
    }

    public long getShortcutId() {
        return shortcutId;
    }

    public void setShortcutId(long shortcutId) {
        this.shortcutId = shortcutId;
    }

}
