package com.snilius.suchquick.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LAUNCHER".
 */
public class Launcher {

    private Long id;
    private String PackageName;

    public Launcher() {
    }

    public Launcher(Long id) {
        this.id = id;
    }

    public Launcher(Long id, String PackageName) {
        this.id = id;
        this.PackageName = PackageName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPackageName() {
        return PackageName;
    }

    public void setPackageName(String PackageName) {
        this.PackageName = PackageName;
    }

}
