package com.snilius.suchquick.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.snilius.suchquick.entity.Shortcut;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SHORTCUT".
*/
public class ShortcutDao extends AbstractDao<Shortcut, Long> {

    public static final String TABLENAME = "SHORTCUT";

    /**
     * Properties of entity Shortcut.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UIName = new Property(1, String.class, "UIName", false, "UINAME");
        public final static Property Name = new Property(2, String.class, "Name", false, "NAME");
        public final static Property ClassName = new Property(3, String.class, "ClassName", false, "CLASS_NAME");
        public final static Property PackageName = new Property(4, String.class, "PackageName", false, "PACKAGE_NAME");
    };

    private DaoSession daoSession;


    public ShortcutDao(DaoConfig config) {
        super(config);
    }
    
    public ShortcutDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SHORTCUT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UINAME\" TEXT," + // 1: UIName
                "\"NAME\" TEXT," + // 2: Name
                "\"CLASS_NAME\" TEXT," + // 3: ClassName
                "\"PACKAGE_NAME\" TEXT);"); // 4: PackageName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SHORTCUT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Shortcut entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String UIName = entity.getUIName();
        if (UIName != null) {
            stmt.bindString(2, UIName);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(3, Name);
        }
 
        String ClassName = entity.getClassName();
        if (ClassName != null) {
            stmt.bindString(4, ClassName);
        }
 
        String PackageName = entity.getPackageName();
        if (PackageName != null) {
            stmt.bindString(5, PackageName);
        }
    }

    @Override
    protected void attachEntity(Shortcut entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Shortcut readEntity(Cursor cursor, int offset) {
        Shortcut entity = new Shortcut( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // UIName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ClassName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // PackageName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Shortcut entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUIName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setClassName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPackageName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Shortcut entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Shortcut entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
