package com.snilius.suchquick.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TILE".
 */
public class Tile {

    private Long id;
    private String Label;
    private String ClickType;
    private String LongClickType;
    private Long ClickActionId;
    private Long LongClickActionId;
    private Integer IconResource;
    private String IconPath;
    private Boolean IconIsPackageDrawable;
    private String SystemTileName;
    private Boolean Enabled;

    public Tile() {
    }

    public Tile(Long id) {
        this.id = id;
    }

    public Tile(Long id, String Label, String ClickType, String LongClickType, Long ClickActionId, Long LongClickActionId, Integer IconResource, String IconPath, Boolean IconIsPackageDrawable, String SystemTileName, Boolean Enabled) {
        this.id = id;
        this.Label = Label;
        this.ClickType = ClickType;
        this.LongClickType = LongClickType;
        this.ClickActionId = ClickActionId;
        this.LongClickActionId = LongClickActionId;
        this.IconResource = IconResource;
        this.IconPath = IconPath;
        this.IconIsPackageDrawable = IconIsPackageDrawable;
        this.SystemTileName = SystemTileName;
        this.Enabled = Enabled;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLabel() {
        return Label;
    }

    public void setLabel(String Label) {
        this.Label = Label;
    }

    public String getClickType() {
        return ClickType;
    }

    public void setClickType(String ClickType) {
        this.ClickType = ClickType;
    }

    public String getLongClickType() {
        return LongClickType;
    }

    public void setLongClickType(String LongClickType) {
        this.LongClickType = LongClickType;
    }

    public Long getClickActionId() {
        return ClickActionId;
    }

    public void setClickActionId(Long ClickActionId) {
        this.ClickActionId = ClickActionId;
    }

    public Long getLongClickActionId() {
        return LongClickActionId;
    }

    public void setLongClickActionId(Long LongClickActionId) {
        this.LongClickActionId = LongClickActionId;
    }

    public Integer getIconResource() {
        return IconResource;
    }

    public void setIconResource(Integer IconResource) {
        this.IconResource = IconResource;
    }

    public String getIconPath() {
        return IconPath;
    }

    public void setIconPath(String IconPath) {
        this.IconPath = IconPath;
    }

    public Boolean getIconIsPackageDrawable() {
        return IconIsPackageDrawable;
    }

    public void setIconIsPackageDrawable(Boolean IconIsPackageDrawable) {
        this.IconIsPackageDrawable = IconIsPackageDrawable;
    }

    public String getSystemTileName() {
        return SystemTileName;
    }

    public void setSystemTileName(String SystemTileName) {
        this.SystemTileName = SystemTileName;
    }

    public Boolean getEnabled() {
        return Enabled;
    }

    public void setEnabled(Boolean Enabled) {
        this.Enabled = Enabled;
    }

}
